FROM php:8.1.16-apache

RUN apt update
RUN apt install -y libicu-dev libonig-dev libzip-dev zip
RUN docker-php-ext-install mysqli pdo pdo_mysql intl mbstring zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer